FROM public.ecr.aws/lambda/python:3.8

# Copy function code
COPY . /asset

WORKDIR /asset

RUN pip install -r requirements.txt -t ./

RUN pip install --upgrade --force-reinstall numpy

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]